# Generated by Django 3.0.8 on 2020-07-26 20:47

from django.db import migrations, models
import schools.models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=schools.models.upload_path),
        ),
    ]
